# Generated by Django 6.0 on 2025-12-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('exposureGroup', models.CharField(max_length=255)),
                ('monthYear', models.CharField(max_length=255)),
                ('medianDayToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('medianHourToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('uniqueReach', models.DecimalField(decimal_places=2, max_digits=20)),
                ('userPurchased', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchases', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalPurchases', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('flagNewToBrand', models.CharField(choices=[('New-to-Brand', 'New-to-Brand'), ('Repeat', 'Repeat')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DodTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('analysisType', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('adProductType', models.CharField(max_length=255)),
                ('impression', models.DecimalField(decimal_places=2, max_digits=20)),
                ('clicks', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalPurchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('flagNewToBrand', models.CharField(choices=[('New-to-Brand', 'New-to-Brand'), ('Repeat', 'Repeat')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PathToPurchaseCampaignMom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('monthYear', models.CharField(max_length=255)),
                ('campaignId', models.CharField(max_length=255)),
                ('campaignName', models.CharField(max_length=255)),
                ('medianDayToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('medianHourToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pathOccurence', models.DecimalField(decimal_places=2, max_digits=20)),
                ('impression', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=20)),
                ('userPurchased', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalPurchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('flagNewToBrand', models.CharField(choices=[('New-to-Brand', 'New-to-Brand'), ('Repeat', 'Repeat')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PathToPurchaseMonthLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('analysisType', models.CharField(max_length=255)),
                ('monthYear', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('medianDayToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('medianHourToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pathOccurence', models.DecimalField(decimal_places=2, max_digits=20)),
                ('impression', models.DecimalField(decimal_places=2, max_digits=20)),
                ('userPurchased', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalPurchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('flagNewToBrand', models.CharField(choices=[('New-to-Brand', 'New-to-Brand'), ('Repeat', 'Repeat')], db_index=True, max_length=20)),
            ],
        ),
    ]
