# Generated by Django 5.2.9 on 2026-01-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audienceoverlap_id_alter_dodtable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienceoverlap',
            name='flagNewToBrand',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='audienceoverlap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dodtable',
            name='flagNewToBrand',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dodtable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pathtopurchasecampaignmom',
            name='flagNewToBrand',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pathtopurchasecampaignmom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pathtopurchasemonthlevel',
            name='flagNewToBrand',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pathtopurchasemonthlevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
