# Generated by Django 5.2.9 on 2026-01-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dodtable_userpurchased_alter_audienceoverlap_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReachFrequencyAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('monthYear', models.CharField(max_length=255)),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reach', models.DecimalField(decimal_places=2, max_digits=20)),
                ('impressions', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchases', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalPurchases', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='audienceoverlap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dodtable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pathtopurchasecampaignmom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pathtopurchasemonthlevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
