# Generated by Django 5.2.9 on 2026-01-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reachfrequencyanalysis_alter_audienceoverlap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reachfrequencyanalysis',
            name='frequency',
            field=models.CharField(max_length=255),
        ),
    ]
