# Generated by Django 5.2.9 on 2026-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reachfrequencyanalysis_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathToPurchaseKeywordLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('monthYear', models.CharField(max_length=255)),
                ('keywordId', models.BigIntegerField()),
                ('keywordName', models.CharField(max_length=500)),
                ('medianDayToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('medianHourToConversion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pathOccurence', models.DecimalField(decimal_places=2, max_digits=20)),
                ('impression', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=20)),
                ('userPurchased', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalPurchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('flagNewToBrand', models.BooleanField(db_index=True)),
            ],
        ),
    ]
